os: linux
dist: bionic
language: python

env:
  # nodemcu uses an old lua version
  - LUA="5.1.4"

before_install:
  # lua toolchain for running tests
  - pip install hererocks
  - hererocks lua_install -rlatest -l${LUA}
  - export PATH=$PATH:$PWD/lua_install/bin # Add directory with all installed binaries to PATH

  # nodemcu toolchain to cross compile
  - git clone --depth 1 https://github.com/nodemcu/nodemcu-firmware.git $HOME/nodemcu-firmware
  - make -C $HOME/nodemcu-firmware/app/lua/luac_cross/
  - export PATH=$PATH:$HOME/nodemcu-firmware

  # tools for building docs
  - pip install mkdocs
  - pip install mkdocs-material

  # tools for building the hub

install:
  - luarocks install busted

script:
  # building and testing the tally
  - cd $TRAVIS_BUILD_DIR/tally
  - make build
  - make test

  # rendering documentation
  - cd $TRAVIS_BUILD_DIR/documentation
  - mkdocs build

  # building and testing the hub
  - cd $TRAVIS_BUILD_DIR/hub
  - npm install --dev
  - npm run test:ci
  - rm -rf node_modules package-lock.json
  - npm install
  - npm run build

  # building the release
  - mkdir -p $TRAVIS_BUILD_DIR/release
  - cp $TRAVIS_BUILD_DIR/Readme.md $TRAVIS_BUILD_DIR/release
  - cp $TRAVIS_BUILD_DIR/LICENSE $TRAVIS_BUILD_DIR/release
  - echo "${TRAVIS_BRANCH}" > $TRAVIS_BUILD_DIR/release/VERSION.txt
  - cp -r $TRAVIS_BUILD_DIR/firmware $TRAVIS_BUILD_DIR/release/firmware
  - cp -r $TRAVIS_BUILD_DIR/tally/out $TRAVIS_BUILD_DIR/release/tally
  - mkdir -p $TRAVIS_BUILD_DIR/release/docs
  - cp -r $TRAVIS_BUILD_DIR/documentation/docs $TRAVIS_BUILD_DIR/release/docs/markdown
  - cp -r $TRAVIS_BUILD_DIR/documentation/site $TRAVIS_BUILD_DIR/release/docs/html
  - cp -r $TRAVIS_BUILD_DIR/hub $TRAVIS_BUILD_DIR/release/hub
  - find $TRAVIS_BUILD_DIR/release -name ".gitignore" -delete

  - cd $TRAVIS_BUILD_DIR/release
  - zip -Jrq "$TRAVIS_BUILD_DIR/wifi-tally-${TRAVIS_BRANCH}.zip" *
  - tar -czf "$TRAVIS_BUILD_DIR/wifi-tally-${TRAVIS_BRANCH}.tar.gz" *
  - tar -cjf "$TRAVIS_BUILD_DIR/wifi-tally-${TRAVIS_BRANCH}.tar.xz" *

deploy:
  - provider: pages
    edge: true
    cleanup: false
    local_dir: $TRAVIS_BUILD_DIR/documentation/site/
    repo: wifi-tally/wifi-tally.github.io
    target_branch: master
    keep_history: false
    token: $GITHUB_TOKEN
    on:
      branch: master
  - provider: releases
    edge: true
    token: $GITHUB_TOKEN
    file_glob: true
    file: "$TRAVIS_BUILD_DIR/wifi-tally-*"
    cleanup: false
    draft: true
    on:
      tags: true

notifications:
  email:
    on_success: change
    on_failure: always
