name: build
on: [ "push" ]
env:
  NODEJS_VERSION: 12
  LUA: "5.1.4"
  NODEMCU_REPO: nodemcu/nodemcu-firmware
  NODEMCU_FIRMWARE: 3.0-master_20200610
  NODEMCU_MODULES: encoder,file,gpio,net,node,pwm2,struct,tmr,uart,wifi,ws2812
defaults:
  run:
    shell: bash
jobs:
  # ###
  #  
  # Detect the version number to use
  # 
  # ###
  setup:
    runs-on: ubuntu-latest
    outputs:
      build_name: ${{ steps.build_name.outputs.build_name }}
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # don't shallow clone! We could not generate a nice build_name otherwise
      - name: Generate build_name
        id: build_name
        run: echo "::set-output name=build_name::$(git describe --tags --always)"
      - name: Output
        run: echo "build_name=${{ steps.build_name.outputs.build_name }}"

  # ###
  # 
  # Building the Javascript hub
  # 
  # ###
  hub-build: 
    needs: setup
    env:
      BUILD_NAME: ${{ needs.setup.outputs.build_name }}
    defaults:
      run:
        working-directory: ./hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2
      - name: Use node.js ${{ env.NODEJS_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODEJS_VERSION }}
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - run: npm ci
      - run: npm run test:ci
      - run: ./scripts/build.sh
      # upload-artifact is obviously not build to upload 20.000 files - it takes AGES
      # so we zip it
      - name: Tar the build
        run: tar -czf "./hub-dist.tar.gz" -C dist/ .
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: hub-dist
          path: "./hub/hub-dist.tar.gz"
          if-no-files-found: error
          retention-days: 2

  # ###
  #
  # luac.cross is needed to build *.lc files that match our firmware
  # 
  # ###
  luaccross:
    name: luac.cross
    runs-on: ubuntu-latest
    steps:
      - name: Cache luac.cross
        id: cache
        uses: actions/cache@v2
        with:
          path: ./luac.cross
          key: ${{ runner.os }}-luaccross-${{ env.NODEMCU_REPO }}-${{ env.NODEMCU_FIRMWARE }}
      - name: Checkout the source code
        uses: actions/checkout@v2
        with:
          repository: ${{ env.NODEMCU_REPO }}
          ref: ${{ env.NODEMCU_FIRMWARE }}
          submodules: recursive
        if: "! steps.cache.outputs.cache-hit"
      - name: make luac.cross
        run: make -C ./app/lua/luac_cross/
        if: "! steps.cache.outputs.cache-hit"
      - name: Archive luac.cross
        uses: actions/upload-artifact@v2
        with:
          name: luaccross
          path: "./luac.cross"
          if-no-files-found: error
          retention-days: 2

  # ###
  # 
  # build the NodeMCU firmware
  #
  # basically we try to recreate https://github.com/marcelstoer/nodemcu-custom-build/blob/master/.travis.yml
  # without the upload and notification logic
  # 
  # ###
  tally-firmware:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/nodemcu-firmware
    env:
      # @see https://github.com/marcelstoer/nodemcu-custom-build/blob/master/.travis.yml for used environment variables
      USER_PROLOG: ""
      X_EMAIL: invalid@example.com
      X_U8G_FONTS: font_6x10,font_chikita
      X_U8G_DISPLAY_I2C: ""
      X_U8G_DISPLAY_SPI: ""
      X_UCG_DISPLAY_SPI: ""
      X_LUA_FLASH_STORE: "0x15000"
      X_SPIFFS_FIXED_LOCATION: "0"
      X_SPIFFS_MAX_FILESYSTEM_SIZE: "0"
      X_SSL_ENABLED: "false"
      X_DEBUG_ENABLED: "false"
      X_FATFS_ENABLED: "false"
    steps:
      - name: set dynamic environment variables
        run: |
          MODULE_HASH=$(echo "${NODEMCU_MODULES}${X_LUA_FLASH_STORE}${X_SSL_ENABLED}${X_DEBUG_ENABLED}${X_FATFS_ENABLED}" | sha512sum | cut -c1-8)
          echo "file_name_float=nodemcu-${{ env.NODEMCU_FIRMWARE }}-${MODULE_HASH}-float.bin" >> $GITHUB_ENV

          echo "TRAVIS_BUILD_DIR=${GITHUB_WORKSPACE}" >> $GITHUB_ENV
          echo "X_MODULES=${NODEMCU_MODULES}" >> $GITHUB_ENV
          echo "X_BRANCH=${NODEMCU_FIRMWARE}" >> $GITHUB_ENV
        working-directory: ./
      - name: Cache luac.cross
        id: cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/nodemcu-firmware/bin/nodemcu-*-float.bin
          key: ${{ runner.os }}-${{ env.file_name_float }}
      - name: Checkout NodeMCU custom build
        if: "! steps.cache.outputs.cache-hit"
        uses: actions/checkout@v2
        with:
          repository: marcelstoer/nodemcu-custom-build
          ref: master
          path: ${{ github.workspace }}
      - name: Checkout NodeMCU firmware
        if: "! steps.cache.outputs.cache-hit"
        uses: actions/checkout@v2
        with:
          repository: ${{ env.NODEMCU_REPO }}
          ref: ${{ env.NODEMCU_FIRMWARE }}
          submodules: recursive
          path: ${{ github.workspace }}/nodemcu-firmware
      - name: Checkout our repo
        if: "! steps.cache.outputs.cache-hit"
        uses: actions/checkout@v2
        with:
          path: ${{ github.workspace }}/wifi-tally
      - name: Install dependencies
        if: "! steps.cache.outputs.cache-hit"
        run: |
          # needed to build esptool.py
          pip install pyserial
          sudo apt-get install srecord
      - name: Build
        if: "! steps.cache.outputs.cache-hit"
        run: |
          # "bash" keyword is necessary, because the shebang points to /bin/env, which does not exist at that place
          bash "${GITHUB_WORKSPACE}/ESP8266/install.sh"
          bash "${GITHUB_WORKSPACE}/ESP8266/before-script.sh"
          bash "${GITHUB_WORKSPACE}/wifi-tally/firmware/script.sh"
      - name: Archive firmware
        uses: actions/upload-artifact@v2
        with:
          name: nodemcu-firmware
          path: ${{ github.workspace }}/nodemcu-firmware/bin/nodemcu-*-float.bin
          if-no-files-found: error
          retention-days: 2


  # ###
  # 
  # Building the code that runs on the tally light
  # 
  # ###
  tally-build:
    runs-on: ubuntu-latest
    needs:
      - setup
      - luaccross
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2
      - name: Cache Lua Environment
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/.lua
            ${{ github.workspace }}/.luarocks
          key: ${{ runner.os }}-lua-${{ env.LUA }}
      - name: Install Lua ${{ env.LUA }}
        uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: ${{ env.LUA }}
      - uses: leafo/gh-actions-luarocks@v4.0.0
      - name: "Log Environment"
        run: |
          echo "::group::Environment Variables"
          env | sort
          echo "::endgroup::"
          echo "::group::Lua"
          which lua
          lua -v
          echo "::endgroup::"
          echo "::group::Luarocks"
          which luarocks
          luarocks --version
          luarocks list
          echo "::endgroup::"
      - uses: actions/download-artifact@v2
        with:
          name: luaccross
          path: /tmp
      - name: Install dependencies
        run: |
          sudo mv /tmp/luac.cross /usr/local/bin
          sudo chmod a+x /usr/local/bin/luac.cross
          luarocks install busted
      - name: Test
        run: make test
        working-directory: ./tally
      - name: Build
        run: make build
        working-directory: ./tally
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: tally-dist
          path: ./tally/out
          if-no-files-found: error
          retention-days: 2


  # ###
  # 
  # Render documentation
  # 
  # ###
  documentation:
    # @TODO: also use ubuntu-latest once Github finished migration to 20.04
    # all we want is a python that is NOT 2.7 - d'oh!
    runs-on: ubuntu-20.04 
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2
      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('${{ github.workspace }}/documentation/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt --user
          echo "${HOME}/.local/bin" >> $GITHUB_PATH
        working-directory: ./documentation
      - name: "Log Environment"
        run: |
          echo "::group::Environment Variables"
          env | sort
          echo "::endgroup::"
          echo "::group::Pip"
          python --version
          python -m pip list
          echo "::endgroup::"
      - name: "Build"
        run: |
          mkdocs build
        working-directory: ./documentation
      - name: Archive HTML
        uses: actions/upload-artifact@v2
        with:
          name: documentation-html
          path: ./documentation/site
          if-no-files-found: error
          retention-days: 2
      - name: Archive markdown
        uses: actions/upload-artifact@v2
        with:
          name: documentation-markdown
          path: ./documentation/docs
          if-no-files-found: error
          retention-days: 2

  # ###
  #
  # Publish the documentation
  #
  # ###
  documentation-publish:
    # only publish when on master branch
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: 
      - documentation
      - setup
    runs-on: ubuntu-latest
    env:
      PAGES_REPO: wifi-tally/wifi-tally.github.io
    steps:
      - name: Checkout Pages
        uses: actions/checkout@v2
        with: 
          repository: ${{ env.PAGES_REPO }}
          ref: master
          token: ${{ secrets.PAGES_TOKEN }}
          path: .
          fetch-depth: 1
      - uses: actions/download-artifact@v2
        with:
          name: documentation-html
          path: .
      - name: Commit changes
        run: |
          if [ $(git status --porcelain | wc -l) == "0" ]; then
            echo "No changes in the documentation"
          else
            git config user.email "bot@xopn.de"
            git config user.name "Xopn Bot"
            git add .
            git commit -m "update for ${{ needs.setup.outputs.build_name }}" --date "$(date)"
          fi
      - name: Push Pages
        uses: ad-m/github-push-action@master
        with:
          repository: ${{ env.PAGES_REPO }}
          github_token: ${{ secrets.PAGES_TOKEN }}
          branch: master

  # ###
  # 
  # Bundle it all together
  # 
  # ###
  bundle:
    needs: 
      - hub-build
      - documentation
      - tally-build
      - tally-firmware
      - setup
    runs-on: ubuntu-latest  
    env:
      BUILD_NAME: ${{ needs.setup.outputs.build_name }}
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get install tree
      - run: |
          mkdir ${GITHUB_WORKSPACE}/dist
          mkdir ${GITHUB_WORKSPACE}/dist/documentation
          mkdir ${GITHUB_WORKSPACE}/dist/firmware
          mkdir ${GITHUB_WORKSPACE}/dist/tally
          mkdir ${GITHUB_WORKSPACE}/dist/hub
      - name: Get HTML documentation
        uses: actions/download-artifact@v2
        with:
          name: documentation-html
          path: ${{ github.workspace }}/dist/documentation/html
      - name: Get Markdown documentation
        uses: actions/download-artifact@v2
        with:
          name: documentation-markdown
          path: ${{ github.workspace }}/dist/documentation/markdown
      - name: Get Firmware
        uses: actions/download-artifact@v2
        with:
          name: nodemcu-firmware
          path: ${{ github.workspace }}/dist/firmware/
      - name: Get Tally
        uses: actions/download-artifact@v2
        with:
          name: tally-dist
          path: ${{ github.workspace }}/dist/tally
      - name: Get Hub
        uses: actions/download-artifact@v2
        with:
          name: hub-dist
          path: ${{ github.workspace }}/dist/hub
      - name: extract hub
        run: |
          tar -xzf hub-dist.tar.gz .
          rm hub-dist.tar.gz
        working-directory: ${{ github.workspace }}/dist/hub
      - name: Copy static files
        run: |
          echo "${BUILD_NAME}" > "${GITHUB_WORKSPACE}/dist/version.txt"
          cp "${GITHUB_WORKSPACE}/Readme.md" "${GITHUB_WORKSPACE}/dist"
          cp "${GITHUB_WORKSPACE}/LICENSE" "${GITHUB_WORKSPACE}/dist"
          cp "${GITHUB_WORKSPACE}/Changelog.md" "${GITHUB_WORKSPACE}/dist"
      - name: Log content and size
        run: |
          tree -I "node_modules"
          du -h -d1
        working-directory: ${{ github.workspace }}/dist
      - name: Zip it
        run: |
          zip -Jrq "${GITHUB_WORKSPACE}/wifi-tally-${BUILD_NAME}.zip" *
          # tar -czf "${GITHUB_WORKSPACE}/wifi-tally-${BUILD_NAME}.tar.gz" *
          # tar -cjf "${GITHUB_WORKSPACE}/wifi-tally-${BUILD_NAME}.tar.xz" *
        working-directory: ${{ github.workspace }}/dist
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: ${{ github.workspace }}/wifi-tally-*.zip
          if-no-files-found: error
          retention-days: 14
      
      



