name: build
on: [ "push" ]
env:
  NODEJS_VERSION: 12
  LUA: "5.1.4"
  NODEMCU_REPO: nodemcu/nodemcu-firmware
  NODEMCU_FIRMWARE: 3.0-master_20200610
  NODEMCU_MODULES: encoder,file,gpio,net,node,pwm2,struct,tmr,uart,wifi,ws2812
defaults:
  run:
    shell: bash
jobs:
  # ###
  #  
  # Detect the version number to use
  # 
  # ###
  setup:
    runs-on: ubuntu-latest
    outputs:
      build_name: ${{ steps.build_name.outputs.build_name }}
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # don't shallow clone! We could not generate a nice build_name otherwise
      - name: Generate build_name
        id: build_name
        run: echo "::set-output name=build_name::$(git describe --tags --always)"
      - name: Output
        run: echo "build_name=${{ steps.build_name.outputs.build_name }}"

  # ###
  # 
  # Building the Javascript hub
  # 
  # ###
  hub-build: 
    if: false # @TODO: temporary. Tuning a different job
    needs: setup
    env:
      BUILD_NAME: ${{ needs.setup.outputs.build_name }}
    defaults:
      run:
        working-directory: ./hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2
      - name: Use node.js ${{ env.NODEJS_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODEJS_VERSION }}
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - run: npm ci
      - run: npm run test:ci
      - run: ./scripts/build.sh
      # upload-artifact is obviously not build to upload 20.000 files - it takes AGES
      # so we zip it
      - name: Tar the build
        run: tar -czf "./hub-dist.tar.gz" dist/
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: hub-dist
          path: "./hub/hub-dist.tar.gz"
          if-no-files-found: error
          retention-days: 2

  # ###
  #
  # luac.cross is needed to build *.lc files that match our firmware
  # 
  # ###
  luaccross:
    name: luac.cross
    runs-on: ubuntu-latest
    steps:
      - name: Cache luac.cross
        id: cache
        uses: actions/cache@v2
        with:
          path: ./luac.cross
          key: ${{ runner.os }}-luaccross-${{ env.NODEMCU_REPO }}-${{ env.NODEMCU_FIRMWARE }}
      - name: Checkout the source code
        uses: actions/checkout@v2
        with:
          repository: ${{ env.NODEMCU_REPO }}
          ref: ${{ env.NODEMCU_FIRMWARE }}
          submodules: recursive
        if: "! steps.cache.outputs.cache-hit"
      - name: make luac.cross
        run: make -C ./app/lua/luac_cross/
        if: "! steps.cache.outputs.cache-hit"
      - name: Archive luac.cross
        uses: actions/upload-artifact@v2
        with:
          name: luaccross
          path: "./luac.cross"
          if-no-files-found: error
          retention-days: 2


  