name: hub-build
on: [ "push" ]
env:
  NODEJS_VERSION: 12
jobs:
  build: 
    runs-on: ubunutu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use node.js ${NODEJS_VERSION}
        uses: actions/setup-node@v1
        with:
          node-version: ${NODEJS_VERSION}
      - run: cd "${GITHUB_WORKSPACE}/hub"
      - name: Log versions
        run: node -v && npm -v
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - run: npm ci
      - run: npm run test:ci
      - run: ./scripts/build.sh
      - name: Zip the build
        run: tar -czf "${HOME}/hub-dist.tar.gz" *
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: hub-dist
          path: "${HOME}/hub-dist.tar.gz"
          retention-days: 2



  